### ISSUE TITLE
DraggableView Container dimensions

### ISSUE THREAD

**Issue by younes0** [Meetic/Shuffle#11]
What would you do to enlarge the DraggableView Container?

![image](https://cloud.githubusercontent.com/assets/886042/15326152/2b4a4b20-1c4d-11e6-9ee6-24c8ed3fc1be.png)

**Comment by florent37** [comment]
please look at the sample https://github.com/Meetic/Shuffle/blob/master/app/src/main/res/layout/activity_horizontal.xml

just add `android:clipChildren="false"` on the Shuffle's container an it should works perfectly 👍
