### ISSUE TITLE
Fixed Height

### ISSUE THREAD

**Issue by pixelbendr** [Meetic/Shuffle#2]
Can the shuffle view be made to "wrap_content" instead of a fixed height? I want to implement it on a chat view where the message length is not capped, if you know what I mean. Any help will be appreciated.

**Comment by florent37** [comment]
yes, look at the wrap_content sample, can you try and send me feedbacks ?

**Comment by pixelbendr** [comment]
@florent37 Ok. I will try and let you know. Thank you

**Comment by pixelbendr** [comment]
it works. thank you
