### ISSUE TITLE
Slow performance on low end smart phones

### ISSUE THREAD

**Issue by pixelbendr** [Meetic/Shuffle#7]
Tested this library on a small screen low end smart phone and the performance is not that great. Is there an option to use hardware acceleration? Regards.

**Comment by florent37** [comment]
I added layer (hardware accelerations) on the 1.0.4, can you check ?

```groovy
compile 'com.meetic.shuffle:shuffle:1.0.4'
compile 'com.meetic.dragueur:dragueur:1.0.2'
```

http://blog.danlew.net/2015/10/20/using-hardware-layers-to-improve-animation-performance/

**Comment by pixelbendr** [comment]
using your blog post I added shuffle.setLayerType(View.LAYER_TYPE_HARDWARE, null); but I was hoping for a setHardwareAcceleration(true) option where the library intuitively knows when to use hardware acceleration. :) Regards. your library is awesome!

**Comment by florent37** [comment]
The libs now use by default hardware accélération, you don't need to add
this Line ;)
Le 11 mai 2016 17:42, "Evans Domina Attafuah" <notifications@github.com> a
écrit :

**Comment by pixelbendr** [comment]
Ok. Thanks for this.
