### ISSUE TITLE
Recycler view item

### ISSUE THREAD

**Issue by pixelbendr** [Meetic/Shuffle#8]
Can this be used as a recycler view item. I have a list of items in my recycler view and I want to make each one of the items swappable not like a dark deck, if you know what I mean. Regards.

**Comment by florent37** [comment]
Each view Will contains a stack of view or each view will be draggable ? In
the second case you should use our library Dragueur, It'll be perfect :)
Le 11 mai 2016 17:39, "Evans Domina Attafuah" <notifications@github.com> a
écrit :

**Comment by pixelbendr** [comment]
Okay. thank you. Regards

**Comment by pixelbendr** [comment]
Can I use Dragueur for google inbox swiping. I have attached an image. The ability to restrict swiping to vertical and add image for left swipe and right swipe.
![gestures-google-inbox jpg](https://cloud.githubusercontent.com/assets/12001207/15189115/9e300aee-1798-11e6-9464-d7a426cd201a.png)

**Comment by florent37** [comment]
Dragueur can be modified to handle this usecase ;) I'll try and come back
with an update
Le 11 mai 2016 18:51, "Evans Domina Attafuah" <notifications@github.com> a
écrit :

**Comment by pixelbendr** [comment]
Okay. thank you. 👍
